name = "core-mmg"
version = "0.2.0"
description = "Mellow Magic Graphics declarative render package."
entry = "src/main.mel"
license = "MIT"
visibility = "public"

authors = ["Mellow Code Team"]
keywords = ["core", "graphics", "mmg", "render", "starter"]
badges = ["official"]
official = true
[dependencies]
